MAPPING_ZEEDIF: dict[str, str] = {
    "1P Traducciones": "1P Trad",
    "Akira Translations": "AkiraTls",
    "Ale ツ Translations": "Ale Tls",
    "Amhelia": "Titania",
    "Anime y Traducciones": "Vlady",
    "AntiHero LN": "AHLN",
    "Artyom": "Artyom",
    "Astral Novel": "AN",
    "Astral Novel Translations": "ASTRAL",
    "Baka-Tsuki Translations Project": "BAKA-TSUKI",
    "Bar Ahnenerbe": "BAhnenerbe",
    "BB-Murdercase": "BB-MURDERCASE",
    "Bell Traducciones": "Bell Trad",
    "Btooom Translations": "BT",
    "Carlos Sánchez": "Malw Dark",
    "Cerberus Translations": "CT",
    "Chibi Chibi Fansub": "CHIBI CHIBI FANSUB",
    "Classroom of Anime": "CoA",
    "Classroom of Anime & Reversi Blog": "COA & Reversi",
    "Cyan Scans": "Cyan Scans",
    "Daily Days Novels": "Daily Days Novels",
    "Dark Guild Fansub": "DGF",
    "Dark Translations": "DarkT",
    "Darkness Dragons Translation": "DDT",
    "Date A Live Translations": "DALT",
    "Date A Live Translations / Einherjar Project": "DALT & EHJR",
    "DeadlySmile": "DEADLLYSMILE",
    "Demential Demon": "Demential Demon",
    "Domen Translations": "DT",
    "Dragoon Translations": "Dragoon Tls",
    "Editorial Panini": "Panini",
    "Einherjar Project": "EHJR",
    "El Reino Hechicero": "RH",
    "Eterno Poder": "ETERNO PODER",
    "Every Translations": "Every Tls",
    "Evil Eye Translations": "EET",
    "Frikigami / Kyuden Translations / Bega Translations": "F & KT & BT",
    "Gambarimasu Translations": "GT",
    "Gashadokai": "Gashadokai",
    "Gashadokai / Kyuden Translations": "KT",
    "Gashadokai / Kyuden Translations / Bega Translations": "KT",
    "GB Traducciones": "GBT",
    "Geomchi Spanish": "GS",
    "Gladheim Translations": "Gladheim",
    "God's Earth Translations": "GET",
    "Gustang Translations": "GustangTL",
    "Happy Bubble Subs": "HAPPY BUBBLE SUBS",
    "Hasu Translations": "HasuTL",
    "HiroLsn Translations": "HiroLsn Tls",
    "Hitoribocchi Translation": "HT",
    "Index Zero": "IZ",
    "J-Light Novel Club": "JLNC",
    "JmCrap Translations": "JM-T",
    "Kai Sakura VENTO": "KSV",
    "Kaleid Word Translations": "CanisLycaon",
    "Kasnia Project": "KP",
    "Kikuslirus Project Team": "KKLS",
    "Kokkokutei Scan KT / Kyuden Translations": "KSKT & KT",
    "Krienlend Gretchen / Kyuden Translations": "Krienlend & KT",
    "Kurosaki-Vizard Translation": "KVTL",
    "Kyuden Translations": "KT",
    "Kyuden Translations / Aoko Translations": "KT & AT",
    "Kyuden Translations / Gashadokai": "KT",
    "Kyuden Translations / MangaProject Fansub": "KT & MPE",
    "Lamp/loversз": "WCT",
    "Lanove Translations": "LANOVE",
    "Legends no Fansub": "Legends no Fansub",
    "Light Novels, Manga and more": "LNMm",
    "MangaProject Fansub": "MPF",
    "MangaProject Fansub / Kyuden Translations": "KT & MPE",
    "Megami no Manga": "MnM",
    "Menudo Fansub": "MENUDO FANSUB",
    "MiraiK – Novelas Ligeras y Más": "MiraiK",
    "MiraiK – Novelas Ligeras y Más & Legends no Fansub": "MK & LnF",
    "MiraiK – Novelas Ligeras y Más × Edens Fairy Fansub": "MK × EFF",
    "Miv Traducciones": "MivT",
    "MT Traducciones": "MT-Trad",
    "Nahucirujano Translations": "NahucirujanoTL",
    "NekoTranslations": "NEKO",
    "Nekura Translation": "NKT",
    "Novel Translation": "NovelTls",
    "Novelas Evillious": "NEvilliousEsp",
    "Novelas TOPCUR": "NTP",
    "Odisea Internautica": "ODISEA INTERNÁUTICA",
    "Onigiri Novels": "Onigiri Novels",
    "Project High Fox": "PROJECT HIGH FOX & LANOVE",
    "R-Fiction": "R-Fiction",
    "Ralevon": "Ralevon",
    "Re: versi Blog": "Re:versi",
    "Rock Valley Novels": "RVN",
    "Rom Traducciones": "ROMT",
    "Rooster Gang Translations": "Rooster Gang",
    "Saekano Translations": "SKNT",
    "Scarlet Aria Translations": "ScarletAriaT",
    "Shadow Moon Translations": "SMT",
    "Shigatsu Translation": "ShT",
    "Shinomiya Translations": "ShinomiyaTL",
    "Shinomiya Translations / Traducciones Fajardo": "Shinomiya",
    "Shinsengumi Translations": "Noukin",
    "ShiroNeko Translations": "SNT",
    "ShiroNeko-Translations / Btooom Translations": "Shironeko x Btooom",
    "SkyNovels": "SN",
    "Taikutsu Translations": "TaikutsuTL",
    "Taikutsu Translations / Kaleid Word Translations": "Taikutsu x Kaleid",
    "Tamashi's Project": "Tamashi´s Project",
    "Titania": "Titania",
    "Todo En Tu Idioma": "TETI",
    "Toradora No Fansub": "Toradora No Fansub",
    "Traducciones Daeldaus": "DAELDAUS",
    "Traducciones Fajardo": "TF",
    "Traducciones Fajardo / Underword Liella Novels": "TF x ULT",
    "Traducciones Ferindrad": "Ferindrad Trad",
    "Traducciones Roberth": "TR",
    "Tradukchion 4 Da Win": "T4DW",
    "True Flames Project": "TFP",
    "Turret Translations": "TurretT",
    "Twin Dragons Light Novels": "TWIN DRAGONS",
    "Uku Translations": "UT",
    "Underword Liella Novels": "UWL novels",
    "VR Work": "VRWork",
    "Wabi-Sabi Translations": "KJY",
    "WisheSubs": "WisheSubs",
    "WolfWolf42": "MiraiK",
    "World Project": "WP",
    "Yumeno Subs": "TMID",
}
